/// <reference types="vite/client" />

// Generated by the `minutes-split` Vite plugin (vite.config.ts) from src/data/minutes.json.
declare module 'virtual:minutes-meta' {
  const meta: Array<Record<string, unknown> & { id: string }>;
  export default meta;
}

declare module 'virtual:minutes-content' {
  const content: Record<string, string>;
  export default content;
}